### PR TITLE
add 1st toeplitz matrix solution

### PR DESCRIPTION
**Pull request by alejo4373**

### CODE REVIEW

**Comment by jabyess** [comment]
Hey alejo, can you make problem and solution filenames match? right now, this problem exists in Problems/MatrixProblems.md. So maybe at the very least make the solution file something like MatrixToeplitzSolution.md, to keep everything consistent.

**Comment by alejo4373** [comment]
@jabyess makes sense

**Comment by alejo4373** [comment]
I created a MatricesProblems inside ArrayProblems to subcategorize them. There are still some Matrices problems in the general MatricesProblems.md and there are other still scattered around in the ArrayProblems folder

**Comment by jabyess** [comment]
wonderful!

**Comment by alejo4373** [comment]
I did not mean to merge I thought I clicked create pull request.

**Pull request merged**
